### ISSUE TITLE
Implement Express Js Router and move all different routes to routes folder.

### ISSUE THREAD

**Issue by gamer-1478** [gamer-1478/chepobin-public#3]
Use Express Js Router and move all different backlinks to different routers, such as /api, to a new file.

**Comment by BlueGhost12** [comment]
there is lots of functions that need exporting from the server.js file. Do you want to export them and use them in the api.js file?

**Comment by gamer-1478** [comment]
hi, i was thinking that the functions could go in a api.js file in a controllers folder, which can be imported wherever needed. and all the endpoints in server.js could go in a router file of apiRoute.js in the routers folder.

**Comment by gamer-1478** [comment]
Would you like to work on this issue?

**Comment by BlueGhost12** [comment]
yes please

**Comment by gamer-1478** [comment]
Sure. I have assigned you.

**Comment by BlueGhost12** [comment]
is it ok if I place functions like makeid, isPasswordProtected, GetChep, SendChep in utilities/api.js file?

**Comment by gamer-1478** [comment]
yeah, but i was thinking more in controller/api.js

**Comment by gamer-1478** [comment]
oh wait, sorry, i thought you were talking about the routes. you can place the functions you are referring too in utilities or helpers. and the routes can go in controllers or routes. @BlueGhost12 sorry about the confusion.

**Comment by BlueGhost12** [comment]
I'm done with the refactoring but I can't test the app. I don't think I have firebase permission for it. I'm getting a "FirebaseError: Missing or insufficient permissions." error.

**Comment by gamer-1478** [comment]
@BlueGhost12 Have you updated the repo to match with this one? The env file has the admin database perms.

**Comment by gamer-1478** [comment]
@BlueGhost12 I'll try your app. you can go ahead and open the pull request and i can comment on that, regarding the code.

**Comment by gamer-1478** [comment]
I am unable to find the updated or rather refactored code in your repository and there are no branches other than main.

**Comment by BlueGhost12** [comment]
sorry I didn't pull earlier. I updated the repo and made the necessary changes and tested the app locally. I also issued a pull request. Please check and let me know if you want more changes
