### ISSUE TITLE
Add RateLimiting

### ISSUE THREAD

**Issue by gamer-1478** [gamer-1478/chepobin-public#6]
Implement a way to rate limit people, on API calls. Use IP to differentiate users.

**Comment by canaryGrapher** [comment]
Can I fix this?

**Comment by AvineshTripathi** [comment]
I too want to work on this

**Comment by gamer-1478** [comment]
@canaryGrapher has already started work. so i will assign him. more issues are coming, so @AvineshTripathi you can take one of those perhaps.
